FROM ubuntu:latest
LABEL jscho <jscho@time-gate.com>

ENV OS_GROUP root
ENV OS_USER root

WORKDIR /opt

# add splunk:splunk user
#RUN groupadd -r $OS_GROUP \
#    && useradd -r -m -g $OS_GROUP $OS_USER \
#    && echo groupadd -r $OS_GROUP \
#    && echo useradd -r -m -g $OS_GROUP $OS_USER

#RUN cd /opt \
#  && RUN sudo apt-get install -y wget sudo tar net-tools
